# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[dep][actions]"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      # at 2:01 am
      time: "02:01"
    commit-message:
      prefix: "[dep][go]"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "binaek"
      - "kaidaguerre"
    labels:
      - "dependencies"
      - "house-keeping"
      
