blank_issues_enabled: true
contact_links:
  - name: Ask a Question on Selefra Community
    url: https://selefra.io/slack
    about: Join Selefra Community Slack to discuss Selefra with other community members.
